/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-library-conventions")
    `java-test-fixtures`
}

sourceSets {
    testFixtures {
        java {
            srcDir("src/testFixtures/java")
        }
    }
}

dependencies {
}
