/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.apache.commons.text.WordUtils;

public class App {
  public static void main(String[] args) {

    var result = WordUtils.capitalize("hello world");
    System.out.println(WordUtils.capitalize(result));
  }
}
